using '../main.bicep'

// Placeholders only. Real subscription/tenant/object IDs and the MI admin
// password are supplied at deploy time via pipeline variables - never here.
param workload = 'i2'
param environment = 'alpha'
param location = 'uksouth'

// Nothing exists in Azure for this environment yet, so Bicep creates the VNet and DNS zones.
// To attach to an existing VNet instead: networkMode = 'existing' and uncomment the three below.
param networkMode = 'new'
param i2AddressPrefix = '10.200.212.0/24'
// param existingVnetName = '<EXISTING_VNET_NAME>'
// param existingVnetResourceGroupName = '<EXISTING_VNET_RG>'
// param privateDnsResourceGroupName = '<PRIVATE_DNS_RG>'

// Entra group: AKS cluster admin, Grafana admin and ACR push. Zeros placeholder is skipped.
param aksAdminGroupObjectId = '00000000-0000-0000-0000-000000000000'
param aksOutboundType = 'loadBalancer'

// Deployer SPN object ID - looked up by scripts/10 in the pipeline, not committed.
param deployerObjectId = ''

// Public IPs allowed through the Key Vault and ACR firewalls. Leave empty here (this repo is
// public): set ALLOWED_TEST_IPS in the i2-alpha variable group instead.
param allowedTestIps = []

// Throwaway environment: destroy and recreate freely (scripts/90-destroy-infra.sh).
// Purge protection off so the Key Vault name can be reused straight away.
param keyVaultPurgeProtection = false

// SQL Managed Instance - smallest sizing for alpha.
param sqlMiAdminLogin = 'i2miadmin'
// sqlMiAdminPassword is a secure param - generated by scripts/10 and kept in Key Vault.
// IMMUTABLE once the MI exists. Must equal Collation in the i2 config's
// InfoStoreNamesSQLServer.properties (scripts/30-build-images.sh prints both and warns).
// Not confirmed by i2 yet: if it changes, destroy and recreate this environment.
param sqlMiCollation = 'Latin1_General_100_CI_AS'
param sqlMiVCores = 4
param sqlMiStorageSizeInGB = 32
param sqlMiZoneRedundant = false
param sqlMiBackupStorageRedundancy = 'LRS'
param sqlMiEntraAdminGroupObjectId = ''
