using '../main.bicep'

// Example environment. Copy to <env>.bicepparam (e.g. dev.bicepparam), set environment to
// the same <env>, and fill in the values. No secrets here: the SQL MI admin password is
// generated by scripts/10-deploy-infra.sh and kept in Key Vault.

param workload = 'i2'
param environment = 'dev'        // must match the file name and I2_ENV / the pipeline's environment
param location = 'uksouth'

// Network. 'new' creates a VNet + private DNS zones for i2 (fresh subscription).
// 'existing' attaches to your VNet: set the three existing* values and make sure
// i2AddressPrefix is already in that VNet's address space.
param networkMode = 'new'
param i2AddressPrefix = '10.200.212.0/24'
// param existingVnetName = '<vnet name>'
// param existingVnetResourceGroupName = '<vnet resource group>'
// param privateDnsResourceGroupName = '<resource group of the privatelink.* DNS zones>'

// Entra group that administers AKS and Grafana (Object ID). Zeros = skipped.
param aksAdminGroupObjectId = '00000000-0000-0000-0000-000000000000'
param aksOutboundType = 'loadBalancer'

// Object ID of the pipeline's service principal (Azure DevOps service connection).
// Gets Key Vault Secrets Officer and AKS cluster admin so later stages can run.
param deployerObjectId = ''

// Public IPs allowed through the Key Vault and ACR firewalls, e.g. the machine that pushes
// images with scripts/30-build-images.sh push. Empty = private endpoints only.
param allowedTestIps = []

// SQL Managed Instance. Collation cannot change after creation: use the Collation value from
// the i2 config's InfoStoreNamesSQLServer.properties (scripts/30-build-images.sh build prints it).
param sqlMiAdminLogin = 'i2miadmin'
param sqlMiCollation = 'Latin1_General_100_CI_AS'
param sqlMiVCores = 8
param sqlMiEntraAdminGroupObjectId = ''

param tags = {
  workload: 'i2-analyze'
  environment: 'dev'
  // owner: '<team>'
  // costCentre: '<code>'
}
